Added a basic page with drag and drop
MadeInShineA/avalgard pull request #2
Opened 2024-12-27 16:44 UTC by NotDonaldPump

I dl a new library to add drag and drop component to our web App and I created a new page to test it.

2024-12-27 17:04 UTC, MadeInShineA requested changes
Everything runs smoothly, could you rename the file and page name from NewP to Garden please ? Thanks

2024-12-29 14:33 UTC, MadeInShineA submitted a review, later dismissed
It's great now, thanks !

2025-01-12 15:48 UTC, GDbateaux approved these changes
nice

2025-01-12 15:55 UTC, MadeInShineA approved these changes
Working! Thx

2025-01-12 16:02 UTC, merged